name: OCaml and Sail Setup

on: [push, pull_request]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OPAM, OCaml, and required libraries
      run: |
        sudo apt install -y software-properties-common
        sudo apt update
        sudo apt install -y opam zlib1g-dev pkg-config libgmp-dev z3 device-tree-compiler
        opam init -y
        opam switch create 4.12.0
        eval $(opam env)

    - name: Clone and Install Sail from JSON branch
      run: |
        opam install dune
        git clone --branch json https://github.com/thinkopenly/sail.git
        cd sail
        make
        sudo make install

    - name: Run make json in current repo and save output
      run: |  
        eval $(opam config env)
        make json > isa.json

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit and push isa.json
      run: |
        git add isa.json
        git commit -m "Add generated isa.json"
        git push